CMS: Particle Discovery Lab + NanoAOD trigger update
cernopendata/opendata.cern.ch pull request #3680
Opened 2024-09-20 18:43 UTC by jmhogan

Two small long-hanging docs updates:
1. Added an educational resource of mine. I chose record 49 since it's empty and adjacent to the group of educational records starting at 50, but could be changed. 
2. Updating the trigger system documentation to describe the NanoAOD branches. 

If it's better to make these changes in the new structure, I have a branch based on master with these same updates.

2024-09-22 19:27 UTC, katilp requested changes
Two minor things: A typo to fix, and is Dockerfile here on purpose.

2024-09-22 19:27 UTC, katilp commented on Dockerfile
Is this Dockerfile part of the PR on purpose?

2024-09-22 19:27 UTC, katilp commented on cernopendata/modules/fixtures/data/docs/cms-guide-trigger-system/cms-guide-trigger-system.md
> +  - trigger bits accosciated to all paths
associated

2024-09-23 14:19 UTC, jmhogan commented on Dockerfile
@katilp updating the xrootd was required to build the container

2024-09-23 16:01 UTC, jmhogan commented
ok @katilp got the fixes in and found the bad whitespace

2024-10-02 18:48 UTC, jmhogan commented
@katilp I guess github wants you to click some button....I can't find anything on my side that I can do to say "resolved"...

2024-10-02 19:06 UTC, katilp approved these changes
Thanks, looks good!

2024-10-10 15:31 UTC, jmhogan commented
@tiborsimko I'm hoping this one is ready to go. Let me know if it would be better for me to close this PR and make the same changes against master or something that uses the new file structure.

2024-10-10 16:31 UTC, tiborsimko commented
> @tiborsimko I'm hoping this one is ready to go. Let me know if it would be better for me to close this PR and make the same changes against master or something that uses the new file structure.

Thanks, I have fixed some trailing dot in a link. It is not necessary for you to rebase against `master`, I have just made a push. I have also pinned the portal infrastructure image to a stable version as part of this merge, so that things are working well off the `master` branch. We'll be soon ready to update 'qa` globally to `master`.  I'll contact you when ready.

2024-10-10 16:50 UTC, tiborsimko approved these changes
Thanks, the record is now deployed on QA: https://opendata-qa.cern.ch/record/49 

(The documentation changes have not been fully deployed on QA yet due to an  [updating issue](https://github.com/cernopendata/cernopendata-portal/issues/65) that we'll hopefully get to streamline in the next few days.)

2024-10-10 16:53 UTC, merged