feat(docs): add TOTEM open data release announcement
cernopendata/opendata.cern.ch pull request #3710
Opened 2024-12-18 10:07 UTC by tiborsimko

2024-12-19 08:08 UTC, grzanka commented
@tiborsimko we would probably introduce few minor changes to the text, I will come with the fix today

2024-12-19 18:01 UTC, grzanka commented on data/docs/totem-releases-first-set-of-open-data/totem-releases-first-set-of-open-data.json
> +      "content": "Today the TOTEM Collaboration has released the first data set for the open data portal. The data taken by TOTEM are used to compute the proton-proton cross section at different coll
```suggestion
      "content": "Today, the TOTEM Collaboration published the first data set on the CERN Open Data Portal. Data recorded by TOTEM is used to measure the total cross section and to study elastic scattering in proton-proton collisions at the LHC for different centre-of-mass energies."
```

2024-12-19 18:01 UTC, grzanka commented on data/docs/totem-releases-first-set-of-open-data/totem-releases-first-set-of-open-data.md
> +proton-proton elastic scattering cross section.
```suggestion
Today, the TOTEM Collaboration published the first data set on the CERN Open Data Portal. Data recorded by TOTEM is used to measure the total cross section and to study elastic scattering in proton-proton collisions at the LHC for different centre-of-mass energies. The data set contains only the information from the Roman-Pot detectors. This data can be used to study elastic scattering at a centre-of-mass energy of 7 TeV. The open data release is accompanied by an example analysis showing how to measure the elastic scattering cross section as a function of the momentum transfer between the incoming protons and the total cross section.
```

2024-12-19 18:02 UTC, grzanka requested changes
I've added few suggestions on the text

2024-12-20 11:15 UTC, tiborsimko commented
> I've added few suggestions on the text

Updated, thanks.

2024-12-20 11:52 UTC, grzanka approved these changes

2025-01-06 08:42 UTC, merged

2025-01-06 09:27 UTC, psaiz commented on data/docs/totem-releases-first-set-of-open-data/totem-releases-first-set-of-open-data.md
> +  <img src="/static/docs/totem-releases-first-set-of-open-data/totem-roman-pots-in-the-lhc-tunnel.jpeg/"
Typo in the src? It ends with a '/'

2025-01-06 09:38 UTC, tiborsimko commented on data/docs/totem-releases-first-set-of-open-data/totem-releases-first-set-of-open-data.md
> +  <img src="/static/docs/totem-releases-first-set-of-open-data/totem-roman-pots-in-the-lhc-tunnel.jpeg/"
Yes, I'll fix it. Locally it works fine, so it went unnoticed...